### ISSUE TITLE
ERROR: Failed to move folder to library (to almost every song)

### ISSUE THREAD

**Issue by hellblazer17** [Geomitron/Bridge#18] opened 2021-06-14 17:49 UTC
There are some songs i was able to download, but for most of them, i get this error. 
I disabled my anti-virus completely, ran the program as administrator, completely deleted the bridge folder in Appdata\Roaming, tried to reinstall, nothing worked.

Apparently, if a song is updated in a compressed format, such as .7z, then this program will not be able to uncompress, then move the files.

**Comment by Geomitron** [comment] 2021-06-14 18:22
I have only seen this happen one other time, and it seems to only happen on a few computers. (I can't reproduce the problem)
More discussion of this can be found here:
https://www.reddit.com/r/CloneHero/comments/m8vr59/bridge_a_desktop_application_for_browsing_and/gytje7j?utm_source=share&utm_medium=web2x&context=3

Could you try reading through and trying my suggestions for fixing this? That should help narrow down the problem so I know what's going wrong.

**Comment by Geomitron** [comment] 2023-12-26 20:18
The download system has been reworked to not use compression formats, so this is probably fixed now. If you still have problems, open another issue or mention it in the Discord.

**Closed by Geomitron** 2023-12-26 20:18 UTC
